### ISSUE TITLE
pause error when helm type 'Application' deletes

### ISSUE THREAD

**Issue by yxzzzxh** [tmax-cloud/cd-operator#63]
헬름 애플리케이션 삭제 시, pause 상태
![image](https://user-images.githubusercontent.com/36444454/141876280-69d9d3af-f616-4034-a930-7c06f83f7c4c.png)

**Comment by changjjjjjjj** [comment]
예전 코드에 helm 필드 정보로 uninstall 해서 err 발생시 panic처리하는 코드가 있었는데 테스트신게 그 버전일 것 같아요 아마??
